# Constants shared across env + event logic

# --- 2018 TRACKS ---
US_ALLIANCE_FIRM = 0
US_ALLIANCE_RELUCTANT = 1
US_ALLIANCE_EMBARGOED = 2

# --- OPS CONSTANTS ---
OP_TRAIN_FORCE = 0; OP_TRAIN_BASE = 1; OP_GARRISON = 2; OP_SWEEP = 3; OP_ASSAULT = 4; OP_TRANSPORT = 5; OP_AIR_STRIKE = 6
OP_RALLY_M26 = 7; OP_MARCH_M26 = 8; OP_ATTACK_M26 = 9; OP_TERROR_M26 = 10; OP_AMBUSH_M26 = 15; OP_KIDNAP_M26 = 16
OP_RALLY_DR = 11; OP_MARCH_DR = 12; OP_ATTACK_DR = 13; OP_TERROR_DR = 14; OP_AMBUSH_DR = 26; OP_ASSASSINATE_DR = 17
OP_RALLY_SYN = 18; OP_MARCH_SYN = 19; OP_ATTACK_SYN = 20; OP_TERROR_SYN = 21; OP_BRIBE_SYN = 22; OP_CONSTRUCT_SYN = 23
OP_EVENT = 24; OP_PASS = 25

# --- PHASED DECISION MODEL (incremental refactor) ---
PHASE_CHOOSE_MAIN = 0
PHASE_CHOOSE_EVENT_SIDE = 1
PHASE_CHOOSE_OP_ACTION = 2
PHASE_CHOOSE_LIMITED_OP_ACTION = 3
PHASE_CHOOSE_SPECIAL_ACTIVITY = 4
PHASE_CHOOSE_TARGET_SPACE = 5
PHASE_CHOOSE_TARGET_FACTION = 6
PHASE_CHOOSE_EVENT_OPTION = 7
PHASE_CHOOSE_TARGET_PIECE = 8
PHASE_PROPAGANDA_REDEPLOY_MENU = 9

# Meta-actions (not part of boardgame ops; used for phase machine)
MAIN_PASS = 0
MAIN_EVENT = 1
MAIN_OPS = 2

EVENT_UNSHADED = 0
EVENT_SHADED = 1
